### ISSUE TITLE
Ошибка при экспорте в файл декларации

### ISSUE THREAD

**Issue by requestinglife** [titov-vv/jal#36]
Добрый день.

Возникла проблема, описываю порядок действий.

1. Создал файл декларации .dc0.
2. Выгрузил операции со счёта IB USD в файл декларации .dc0, операции в долларах успешно добавились. Тут всё ок.
3. Далее мне нужно добавить в эту же декларацию данные по другой валюте. Запускаю выгрузку в этот же файл со второго счёта IB CAD (аккаунт IB тот же, но валюта другая, канадский доллар), получаю ошибку и файл не сохраняется

2021-04-08 22:18:34,904 - ERROR - Currency isn't known for tax form: CAD
2021-04-08 22:18:34,909 - CRITICAL - EXCEPTION: ['Traceback (most recent call last):\n', '  File "C:\\Users\\request\\AppData\\Roaming\\Python\\Python39\\site-packages\\jal\\reports\\dlsg.py", line 232, in get_country_currency\n    currency_code = self.currencies[currency_name]\n', "KeyError: 'CAD'\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\request\\AppData\\Roaming\\Python\\Python39\\site-packages\\jal\\reports\\taxes.py", line 262, in showTaxesDialog\n    self.save2file(dialog.xls_filename, dialog.year, dialog.account, dlsg_update=dialog.update_dlsg,\n', '  File "C:\\Users\\request\\AppData\\Roaming\\Python\\Python39\\site-packages\\jal\\reports\\taxes.py", line 296, in save2file\n    next_row = report_description[self.RPT_METHOD]()\n', '  File "C:\\Users\\request\\AppData\\Roaming\\Python\\Python39\\site-packages\\jal\\reports\\taxes.py", line 522, in prepare_stocks_and_etf\n    self.statement.add_stock_profit(deal[\'country_code\'], self.broker_name, deal[\'cs_date\'],\n', '  File "C:\\Users\\request\\AppData\\Roaming\\Python\\Python39\\site-packages\\jal\\reports\\dlsg.py", line 216, in add_stock_profit\n    country_code, currency_code = self.get_country_currency(country, currency_name)\n', '  File "C:\\Users\\request\\AppData\\Roaming\\Python\\Python39\\site-packages\\jal\\reports\\dlsg.py", line 235, in get_country_currency\n    raise ValueError\n', 'ValueError\n']

![2021-04-08_22-18-30](https://user-images.githubusercontent.com/82116834/114071616-c0bec980-98ba-11eb-96e1-eead01e4d975.png)

**Comment by titov-vv** [comment]
Это не совсем ошибка, просто для декларации нужны трёхзначные коды валют. Я пока не искал, можно ли их взять где-то автоматически, поэтому приходится время от времени добавлять руками (а в интерфейса это тоже пока не добавил).
Само сообщение об ошибке подправлю, ну и второе конечно тоже не должно возникать, исправлю, чтобы не пугало.

**Comment by requestinglife** [comment]
Спасибо, жду релиз:)
