### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by amalcev** [titov-vv/jal#58]
While trying to install I got the following error. Could you help please?

```
pip install jal
Collecting jal
  Downloading jal-2022.2.1.tar.gz (246 kB)
     |████████████████████████████████| 246 kB 364 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\user\AppData\Local\Programs\Python\Python310-32\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-w5y1oca_\\jal_e495349d45a6424b91feaa5083d27738\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-w5y1oca_\\jal_e495349d45a6424b91feaa5083d27738\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-imq5fsbv'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-w5y1oca_\jal_e495349d45a6424b91feaa5083d27738\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-w5y1oca_\jal_e495349d45a6424b91feaa5083d27738\setup.py", line 25, in <module>
        long_description=read('jal/pypi_description.md'),
      File "C:\Users\user\AppData\Local\Temp\pip-install-w5y1oca_\jal_e495349d45a6424b91feaa5083d27738\setup.py", line 8, in read
        return fp.read()
      File "C:\Users\user\AppData\Local\Programs\Python\Python310-32\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1947: character maps to <undefined>
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bb/14/407a63bfc70be48999ae66713bd34c5435e12a22854ad4c2169a1c54fd8d/jal-2022.2.1.tar.gz#sha256=d7fd15219d1f323cfbb1f1f8c12e4f1631dc7e9c1508014bc83d5c72dd89671b (from https://pypi.org/simple/jal/) (requires-python:>=3.8.1). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Using different command:
```
python "C:\jal-master\setup.py"
Traceback (most recent call last):
  File "C:\jal-master\setup.py", line 25, in <module>
    long_description=read('jal/pypi_description.md'),
  File "C:\jal-master\setup.py", line 8, in read
    return fp.read()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1947: character maps to <undefined>
```

After that I corrected "open" in setup.py:
`open(os.path.join(here, rel_path), encoding="utf-8")`
and got another error:
```
python "C:\jal-master\setup.py"
C:\Users\user\AppData\Local\Programs\Python\Python310-32\lib\site-packages\setuptools\dist.py:487: UserWarning: Normalizing '2022.02.1' to '2022.2.1'
  warnings.warn(tmpl.format(**locals()))
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

**Comment by titov-vv** [comment]
I think I know where the error is. 
I expect to fix it in 2022.02.2 and will try to publish it around weekend.

**Comment by titov-vv** [comment]
Pardon, I missed the end of your comment reading from phone. 
I think you did it right but you need to add the same `encoding="utf8"` in read() call at liine #12 of setup.py
Could you try it, please?

**Comment by amalcev** [comment]
@titov-vv not sure I did this right:
`read(rel_path, encoding="utf-8").splitlines()`

I got the following error:
```
Traceback (most recent call last):
  File "C:\jal-master\setup.py", line 21, in <module>
    version=get_version("jal/__init__.py"),
  File "C:\jal-master\setup.py", line 12, in get_version
    for line in read(rel_path, encoding="utf-8").splitlines():
TypeError: read() got an unexpected keyword argument 'encoding'
```

**Comment by titov-vv** [comment]
Pardon, it seems I haven't woke up yet... First correction of `open()` in line 7 was the right one. 
"Normalizing" error is another one, I'll check it more.

**Comment by titov-vv** [comment]
It appears I read an old [PEP 440](https://www.python.org/dev/peps/pep-0440/) before they corrected manual according to https://github.com/pypa/setuptools/issues/302#issuecomment-514109089
I think I'll need to correction versioning scheme and get rid of leading zero in month part of the version in order to be compatible with PEP 440.

**Comment by titov-vv** [comment]
Issue was closed automatically due to commit message. I'm not 100% that problem `UserWarning: Normalizing '2022.02.1' to '2022.2.1'` is fixed but I think it is.

**Comment by amalcev** [comment]
@titov-vv just tried to install new version and got the following:

```
python "C:\jal-master\setup.py"
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

Am I doing something wrong?

**Comment by titov-vv** [comment]
As discussed in telegram - you need to tun `setup.py install` this is why error "no command supplied" is reported.
But you have a bigger problem with installation of `numpy` package.
