### ISSUE TITLE
Error after db upgrade

### ISSUE THREAD

**Issue by gdm120** [titov-vv/jal#74]
I've downloaded new version and unpacked it on top of the previous one.(2022.03)
On the first run jal proposed to upgrade database to new format and I agreed.
Everything ended with exception, which now repeats for every run:

(base) c:\Users\Roman\jal-master>python run.py
Traceback (most recent call last):
  File "c:\Users\Roman\jal-master\run.py", line 6, in <module>
    main()
  File "c:\Users\Roman\jal-master\jal\jal.py", line 46, in main
    window = MainWindow(language)
  File "c:\Users\Roman\jal-master\jal\widgets\main_window.py", line 58, in __init__
    self.statements = Statements(self)
  File "c:\Users\Roman\jal-master\jal\data_import\statements.py", line 23, in __init__
    self.loadStatementsList()
  File "c:\Users\Roman\jal-master\jal\data_import\statements.py", line 30, in loadStatementsList
    module = importlib.import_module(f"jal.data_import.broker_statements.{module_name}")
  File "C:\Users\Roman\miniconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\Users\Roman\jal-master\jal\data_import\broker_statements\quik_html_old.py", line 11, in <module>
    from jal.constants import DividendSubtype
ImportError: cannot import name 'DividendSubtype' from 'jal.constants' (c:\Users\Roman\jal-master\jal\constants.py)
Exception ignored in atexit callback: <function shutdown at 0x000001F000D7F880>
Traceback (most recent call last):
  File "C:\Users\Roman\miniconda3\lib\logging\__init__.py", line 2183, in shutdown
    h.close()
RuntimeError: Internal C++ object (LogViewer) already deleted.

[env.txt](https://github.com/titov-vv/jal/files/11109785/env.txt)

**Comment by titov-vv** [comment]
The problem is not related with DB upgrade itself. 
Module _quik_html_old.py_ was deprecated and not updated for some time already. It finally became incompatible with recent code changes and I removed it completely.
It appears that the file was kept on your disk as you unpacked new jal version on top of the previous one. I.e. new files were added, updated files were overwritten but outdated files were not deleted. So you got an error as _quik_html_old.py_ isn't compatible with other code.
You corrected the problem in a right way. But I have no idea how to prevent it from happening... If you have a proposal - I'm ready to listen. If not, I think I'll close this issue as no fault.

**Comment by gdm120** [comment]
Thank you for prompt reply. May be you can define strict list of importers, so that new version wouldn't try to use the old ones.

**Comment by titov-vv** [comment]
The are no limitation done intentionally - jal will try to load every "plugin" from import directory. It allows someone to create his/her own module for a specific import and don't share it publicly. 
But anyway, your experience helped to re-think it and I understood that current implementation assumes that all modules are syntactically correct there. I'll try to make better error handling and simply ignore modules that raise exceptions during startup process.
