### ISSUE TITLE
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

### ISSUE THREAD

**Issue by titov-vv** [titov-vv/jal#76]
JAL doesn't start after PySide6 upgrade to 6.5.0 with following errors:
`Traceback (most recent call last):
  File "../jal/run.py", line 6, in <module>
    main()
  File "../jal/jal/jal.py", line 46, in main
    window = MainWindow(language)
  File "../jal/jal/widgets/main_window.py", line 36, in __init__
    QMainWindow.__init__(self, None)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)`

Everything works fine with PySide6 6.4.3 but doesn't work after the upgrade to 6.5.0. The reason isn't clear.

**Comment by titov-vv** [comment]
This is a bug in PySide 6.5.0.
But Jal needs changes to work properly with PySide 6.5.0 anyway.

**Comment by titov-vv** [comment]
Fixed with recent changes to UI-classes and LogViewer.
