### ISSUE TITLE
unable to open database file Error opening database

### ISSUE THREAD

**Issue by alexminder** [titov-vv/jal#88]
`jal-2024.7.1`, `qt-6.7.2`, `python-3.12`

```bash
$ jal
QSqlDatabasePrivate::database: unable to open database: "unable to open database file Error opening database"
CRITICAL:root:DB connection 'JAL.DB' is not open
QSqlQuery::prepare: database not open
ERROR:root:SQL query preparation failure: '' for query 'SELECT sqlite_version()'
CRITICAL:root:EXCEPTION: ['Traceback (most recent call last):\n', '  File "/usr/lib/python-exec/python3.12/jal", line 8, in <module>\n    sys.exit(main())\n             ^^^^^^\n', '  File "/usr/lib/python3.12/site-packages/jal/jal.py", line 24, in main\n    error = JalDB().init_db()\n            ^^^^^^^^^^^^^^^^^\n', '  File "/usr/lib/python3.12/site-packages/jal/db/db.py", line 123, in init_db\n    sqlite_version = self.get_engine_version()\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/usr/lib/python3.12/site-packages/jal/db/db.py", line 160, in get_engine_version\n    return self._read("SELECT sqlite_version()")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/usr/lib/python3.12/site-packages/jal/db/db.py", line 227, in _read\n    if query.next():\n       ^^^^^^^^^^\n', "AttributeError: 'NoneType' object has no attribute 'next'\n"]
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.12/jal", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/jal/jal.py", line 24, in main
    error = JalDB().init_db()
            ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/jal/db/db.py", line 123, in init_db
    sqlite_version = self.get_engine_version()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/jal/db/db.py", line 160, in get_engine_version
    return self._read("SELECT sqlite_version()")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/jal/db/db.py", line 227, in _read
    if query.next():
       ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'next'
```

**Comment by titov-vv** [comment]
Hi, I'm not sure which language to use in my repsonse so will write in both. 

Could you please provide more details about how you ran jal? I.e.: operation system, installed sqlite version, was it first run? 

Добрый день,
Можете написать чуть больше подробностей о проблеме: на какой системе запускаете, какая версия sqlite установлена? Я так подозреваю, что это первый запуск - правильно?

**Comment by alexminder** [comment]
Добрый день!

Первый запуск.

`Gentoo Linux`, `pyside6-6.7.2`

Ebuild  с который написал для приложени: https://git.millerson.name/millerson.name/gentoo-overlay/src/branch/master/app-office/jal/jal-2024.7.1.ebuild

```bash
$ sqlite3
SQLite version 3.44.2 2023-11-24 11:41:44
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite>  SELECT sqlite_version();
3.44.2
sqlite> .exit
```

**Comment by titov-vv** [comment]
Привет.
Понятно. С Gentoo я лет 20 дела не имел... У меня есть одно подозрение - я проверю его сегодня/завтра - но всё-равно не уверен в нём ли дело. Если не получится, то надо будет подумать и поэкспериментировать.
Вам удобно будет мне в почту или телегу написать? - думаю там просто быстрее получится общаться и понять в чём дело.

**Comment by alexminder** [comment]
Проблема оказалась в том, что файл БД пытался создаваться там, где не было прав на запись у приложения.
Пока сделал костыль:
```diff
diff -ur jal-2024.7.1.orig/jal/db/db.py jal-2024.7.1.new/jal/db/db.py
--- jal-2024.7.1.orig/jal/db/db.py	2024-08-01 00:26:42.000000000 +0300
+++ jal-2024.7.1.new/jal/db/db.py	2024-08-18 09:26:30.292027271 +0300
@@ -104,7 +104,9 @@
         if "pytest" in sys.modules:
             return os.environ['JAL_TEST_PATH'] + os.sep + Setup.DB_PATH  # Use custom path if in test environment
         else:
-            return JalDB.get_app_path() + Setup.DB_PATH
+            DBfilepath = os.path.expanduser('~') + '/.jal/' + Setup.DB_PATH
+            os.makedirs(os.path.dirname(DBfilepath), exist_ok=True)
+            return DBfilepath
 
     # -------------------------------------------------------------------------------------------------------------------
     # This function:

```

**Comment by titov-vv** [comment]
Понял, спасибо за анализ. Сделаю, чтобы можно было конфигурировать расположение базы данных

**Comment by titov-vv** [comment]
Теперь поддерживается возможность указать расположение базы данных в jal.ini.
